#!/usr/bin/env python3
"""Extract first repository metadata item from dist/data/repos.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract first repo metadata item")
    parser.add_argument(
        "--repos-json",
        default="dist/data/repos.json",
        help="Path to repos.json generated by backend export",
    )
    parser.add_argument(
        "--output",
        default="out/meta.json",
        help="Output path for extracted metadata",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repos_json = Path(args.repos_json)
    output = Path(args.output)

    with repos_json.open("r", encoding="utf-8") as f:
        items = json.load(f)

    if not items:
        raise SystemExit(f"{repos_json} is empty")

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as f:
        json.dump(items[0], f, ensure_ascii=False)


if __name__ == "__main__":
    main()
